--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Debian 16.9-1.pgdg120+1)
-- Dumped by pg_dump version 16.9 (Debian 16.9-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: destinations; Type: TABLE; Schema: public; Owner: travel_user
--

CREATE TABLE public.destinations (
    id character varying(255) NOT NULL,
    city character varying(255),
    country character varying(255),
    state character varying(255)
);


ALTER TABLE public.destinations OWNER TO travel_user;

--
-- Name: places; Type: TABLE; Schema: public; Owner: travel_user
--

CREATE TABLE public.places (
    id character varying(255) NOT NULL,
    category character varying(255),
    city character varying(255),
    country character varying(255),
    description character varying(255),
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    name character varying(255),
    rating double precision NOT NULL,
    source character varying(255),
    trip_id character varying(255)
);


ALTER TABLE public.places OWNER TO travel_user;

--
-- Name: roles; Type: TABLE; Schema: public; Owner: travel_user
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.roles OWNER TO travel_user;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: travel_user
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trip_place; Type: TABLE; Schema: public; Owner: travel_user
--

CREATE TABLE public.trip_place (
    id character varying(255) NOT NULL,
    notes character varying(255),
    order_in_trip integer,
    place_id character varying(255),
    visit_date date,
    trip_id character varying(255)
);


ALTER TABLE public.trip_place OWNER TO travel_user;

--
-- Name: trips; Type: TABLE; Schema: public; Owner: travel_user
--

CREATE TABLE public.trips (
    id character varying(255) NOT NULL,
    budget double precision NOT NULL,
    end_date date,
    name character varying(255),
    start_date date,
    user_id character varying(255) NOT NULL,
    destination_id character varying(255)
);


ALTER TABLE public.trips OWNER TO travel_user;

--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: travel_user
--

CREATE TABLE public.user_roles (
    user_id character varying(255) NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_roles OWNER TO travel_user;

--
-- Name: users; Type: TABLE; Schema: public; Owner: travel_user
--

CREATE TABLE public.users (
    id character varying(255) NOT NULL,
    email character varying(255),
    enabled boolean NOT NULL,
    name character varying(255),
    password character varying(255)
);


ALTER TABLE public.users OWNER TO travel_user;

--
-- Name: destinations destinations_pkey; Type: CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.destinations
    ADD CONSTRAINT destinations_pkey PRIMARY KEY (id);


--
-- Name: places places_pkey; Type: CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.places
    ADD CONSTRAINT places_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: trip_place trip_place_pkey; Type: CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.trip_place
    ADD CONSTRAINT trip_place_pkey PRIMARY KEY (id);


--
-- Name: trips trips_pkey; Type: CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);


--
-- Name: trips uk1ajfhrncuf211a3ik3u4exu00; Type: CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT uk1ajfhrncuf211a3ik3u4exu00 UNIQUE (destination_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_trip_place_place_id; Type: INDEX; Schema: public; Owner: travel_user
--

CREATE INDEX idx_trip_place_place_id ON public.trip_place USING btree (place_id);


--
-- Name: idx_trip_place_trip_id; Type: INDEX; Schema: public; Owner: travel_user
--

CREATE INDEX idx_trip_place_trip_id ON public.trip_place USING btree (trip_id);


--
-- Name: idx_trips_user_id; Type: INDEX; Schema: public; Owner: travel_user
--

CREATE INDEX idx_trips_user_id ON public.trips USING btree (user_id);


--
-- Name: trip_place fk954igupc3q7hdsndan9oa0lm4; Type: FK CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.trip_place
    ADD CONSTRAINT fk954igupc3q7hdsndan9oa0lm4 FOREIGN KEY (trip_id) REFERENCES public.trips(id);


--
-- Name: user_roles fkh8ciramu9cc9q3qcqiv4ue8a6; Type: FK CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: trips fkqyeck80yftx02q35eo8s1ebv2; Type: FK CONSTRAINT; Schema: public; Owner: travel_user
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT fkqyeck80yftx02q35eo8s1ebv2 FOREIGN KEY (destination_id) REFERENCES public.destinations(id);


--
-- PostgreSQL database dump complete
--

